### ISSUE TITLE
object is not a function

### ISSUE THREAD

**Issue by derhyl** [revolunet/node-sellsy#3]
Hi, 
I am having problems to start with the API as I cannot authenticate. What did I miss? Or is there anything wrong? I simply installed the node module and runned the first part of your example script... This is what i get:

var sellsy = new Sellsy({
        ^
TypeError: object is not a function
    at Object.<anonymous> (/home/ludell/Public/digipipeCrx/sellsyApi/main.js:3:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Thanks a lot, 
Lucien

**Comment by revolunet** [comment]
do you use npm ?
where does `Sellsy` variable come from ?

it should be required like this : `var Sellsy = require('node-sellsy')`

**Comment by derhyl** [comment]
it is exactly where it comes from... and npm install with --save has been done previously :/

**Comment by revolunet** [comment]
indeed, sorry for this, just pushed a v1.2.0 that should solve that import issue

**Comment by derhyl** [comment]
:) thanks!
