### ISSUE TITLE
Unhandled JSON parsing error

### ISSUE THREAD

**Issue by nfroidure** [revolunet/node-sellsy#5]
When Sellsy returns bad JSON like this:
```js
<pre>
<style>
div.Debug {text-align: left;word-wrap: break-word;overflow-y: scroll;max-height: 500px;}
div.Debug pre { margin-left: 200px;padding:10px; color:#333333; background-color:#DDDDDD; font-family: mono; font-size: 9pt; line-height:10pt;}
div.Debug .file {color:#060606; font-style:italic; padding-bottom:5px;}
div.Debug .message {color:#006600;}
div.Debug .stabilo {background-color:yellow; padding-left:3px; padding-right:3px;}
div.Debug .caller {color:#C0222A; list-style:square; margin:5px; line-height:9pt;}
div.Debug pre strong em {color:#993300;}
/* fin styles pour Debug */
</style>


<!-- START DEBUG -->
<div class="Debug">
<pre>
<div class="file">Into : _requires.php on line 75</div><span class="message"></span> => String
{
    [] => Documents
}
<ul class="caller"><li class="caller">Call : <b>saasAutoload()</b></li><li class="caller">Call : <b>spl_autoload_call()</b></li><li class="caller">Call : <b>class_exists()</b><br>Into : <i>/home/myfacture/public_html/saas/api/api/0/core/controller/Process.class.php on line 136</i></li><li class="caller">Call : <b>Process::route()</b><br>Into : <i>/home/myfacture/public_html/saas/api/api/0/core/controller/Provider.class.php on line 275</i></li><li class="caller">Call : <b>Provider::runProcess()</b><br>Into : <i>/home/myfacture/public_html/saas/api/api/0/index.php on line 33</i></li></ul></pre>
</div>
<!-- END DEBUG -->

</pre>/home/myfacture/public_html/saas/engine_v2/framework/_requires.php l.76 : Unable to retrieve class {Documents} <pre>#0 [internal function]: saasAutoload('Documents')
#1 [internal function]: spl_autoload_call('Documents')
#2 /home/myfacture/public_html/saas/api/api/0/core/controller/Process.class.php(136): class_exists('Documents')
#3 /home/myfacture/public_html/saas/api/api/0/core/controller/Provider.class.php(275): Process->route()
#4 /home/myfacture/public_html/saas/api/api/0/index.php(33): Provider->runProcess()
#5 {main}</pre>
```

The NodeJS process crash. Here is the stack trace:
```
log.js:54 Uncaught Exception: SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /home/nfroidure/sencrop/infrastructure-sencrop/node_modules/node-sellsy/dist/index.js:76:20
    at passBackControl (/home/nfroidure/sencrop/infrastructure-sencrop/node_modules/oauth/lib/oauth.js:390:11)
    at IncomingMessage.<anonymous> (/home/nfroidure/sencrop/infrastructure-sencrop/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

The Sellsy API is kinda weird to return HTML but I think this module should handle bad JSON anyway. I can make a PR if needed.

Thanks for this module ;).

**Comment by revolunet** [comment]
c'est le debug en prod chez sellsy ??

**Comment by revolunet** [comment]
yes, would be great to have a PR to handle these cases, thanks; available for assistance if needed

**Comment by nfroidure** [comment]
@revolunet it is a production debugging trace ;).

**Comment by rneuter** [comment]
Hi,

We fixed this issue this week. A debugging trace was present in our autoloader and was called if you tried to call an inexistent endpoints class (here Document**s** instead of Document).

Of course our system don't print trace in production, this was a mistake...

Thank you for your feedback !

**Comment by revolunet** [comment]
yess! thanks a lot !
